// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:be6952f0-cdf4-48df-8299-59f0c11e658e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_up5TcUANA",
    "aws_user_pools_web_client_id": "3pns2rna38g3fpjj3betifh2pu",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://hk4scduk10.execute-api.us-west-2.amazonaws.com/local",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
